Azure-Samples/ansible-playbooks

AppGatewayCreate.yml
KeyVaultCreate.yml
MySQLDatabaseCreate.yml
PostgreSQLDatabaseCreate.yml

* Adding 4 more samples
```
[ ] Yes
[ x] No
```
```
[ ] Bugfix
[x ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```
```
cd [repo-name]
npm install
```
```
```
* ...

adding 4 more samples

---

.travis.yml
ACIcreatewithACR.yml
AppGatewayCreate.yml
KeyVaultCreate.yml
MySQLDatabaseCreate.yml
PostgreSQLDatabaseCreate.yml
SQLCreate.yml
VMCreate.yml
VMCreateSSH.yml
VMCreateWindows.yml
VMScaleSetCreate.yml
create_virtualmachine_with_subnet_in_different_resource_group.yml
networkinterface_with_virtualnetwork_in_another_resource_group.yml

add travis.yml for test.
Plan is to run playbooks in this repo weekly. It's not time-consuming because total around 10 playbooks, and each playbook do relatively one scenario.
```
[ ] No
```
```
[ ] CI
```
```
cd [repo-name]
npm install
```
```
```
* ...

add .travis.yml for test

---

.travis.yml
ACIcreatewithACR.yml
KeyVaultCreate.yml
README.md
SQLCreate.yml
VMCreate.yml
VMCreateSSH.yml
VMCreateWindows.yml
create_virtualmachine_with_subnet_in_different_resource_group.yml
networkinterface_with_virtualnetwork_in_another_resource_group.yml

* ...
1. docker, git not installed
2. filed issues for failed playbooks
```
[ ] No
```
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```
```
cd [repo-name]
npm install
```
```
```
* ...

test ci , fix issues found

---

.travis.yml

* ...
fix syntax error in travis.yml
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```
```
cd [repo-name]
npm install
```
```
```
* ...

fix syntax error in travis.yml

---

.travis.yml

* ...
remove resource group vars.
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
```
```
cd [repo-name]
npm install
```
```
```
* ...

remove resource group var

---

vmss/vmss-setup-deploy.yml

* ...
add  build sample app, and deploy step to vmss sample.
```
[ ] No
```
```
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

add deploy step to vmss sample

---

AppGatewayCreate.yml

The purpose of this PR is to:
- make sample compatible with newest application gateway module in azure_preview_modules
- make it more real-life sample
- create proper backend (two container instances with httpd)
- create proper public ip address, so the application is accessible via browser
```bash
```
```bash
```
```
```
```bash
ansible-playbook …
```

improved app gateway sample

---

KeyVaultCreate.yml

* ...
fix keyvault test by getting object id from env, instead of hardcode, not sure what's the hardcode one
```bash
```
```bash
```
```
```
```bash
```

fix keyvault test

---

SQLCreate.retry
SQLCreate.yml

Improve instructions, and remove role reference as not necessary any longer.
```bash
```
```bash
```
```
```
```bash
```

Sql server sample updated

---

vmss/vmss-setup-deploy.yml

* ...
update vmss sample helloworld repo url.
```bash
```
```bash
```
```
```
```bash
```

update sample repo url

---

.travis.yml
aci_create_with_acr.yml
appgateway_create.yml
azure_rm_subnet/sub_with_nsg_in_other_rg1.yml
azure_rm_subnet/sub_with_nsg_in_other_rg2.yml
vmss/vmss-ping.yml
vmss/vmss-scale-out.yml
vmss/vmss-setup-deploy.yml
vmss/vmss-test-url.yml

* ...
update  .travis.yml to test yaml file in subfolder.
Will update travis.yml in next PR to test changed ymls only.
```bash
```
```bash
```
```
```
```bash
```

test ymls in subfolder

---

.travis.yml
networkinterface_with_virtualnetwork_in_another_resource_group.yml

* ...
test updated yml files only.
```bash
```
```bash
```
```
```
```bash
```

test updated yml file only

---

vm_create_with_nic_in_other_rg.yml

* ...
```bash
```
```bash
```
```
```
```bash
```

vm_create_with_nic_in_other_rg

---

.travis.yml
vm_create_image.yml

* ...
```bash
```
```bash
```
```
```
```bash
```

adding vm_create_image sample

---

README.md

* Removes indentation on some code blocks for running this application. It was not consistent with other blocks in the same file.
```bash
```
```bash
```
```
```
```bash
```

Remove indentation for some code snippets

---

azure_rm_subnet/sub_with_nsg_in_other_rg1.yml
azure_rm_subnet/sub_with_nsg_in_other_rg2.yml
azure_rm_subnet/subnet_with_nsg.yml
rest/eventhub-create.yml
vm_create_existingvnet_deployjavaapp.yml
vm_create_image.yml
vmss/vmss-create.yml
vmss/vmss-scale-out.yml
vmss/vmss-setup-deploy.yml
vmss/vmss-test-url.yml
webapp.yml

* ...
rename variable names
```bash
```
```bash
```
```
```
```bash
```

rename variable names

---

appserviceplan_scale.yml

* ...
sample to scale app service plan.
```bash
```
```bash
```
```
```
```bash
```

sample to scale app service plan

---

README.md

Might be confusing: cloud hell or cloud shell, as microsoft cloud definetly is not the hell..
* ...
```bash
```
```bash
```
```
```
```bash
```

Fixed typo in "Using Azure cloud shell in Visual Studio Code"

---

vnet_peering.yml

* ...
add vnet peering sample
```bash
```
```bash
```
```
```
```bash
```

add vnet peering sample

---

vnet_peering.yml

* ...
fix sample in sample.
```bash
```
```bash
```
```
```
```bash
```

fix name in sample

---

postgresql_create.yml

Updated postgresql_create.yml
* ...
```bash
```
```bash
```
```
```
```bash
```

Updated postgresql_create yaml

---

vmss_extension/01-create-vmss.yml
vmss_extension/02-setup-httpd.yml
vmss_extension/03-update-instances.yml

e2e demo for vmss extension
```bash
```
```bash
```
```
```
```bash
```

adding vmss extension demo

---

rediscache.yml

add redis cache sample playbook.
```bash
```
```bash
```
```
```
```bash
```

add redis cache sample

---

README.md

* ...
Check link takes you to correct destination, which is <http://docs.ansible.com/ansible/latest/intro_installation.html>.

Fixed link with double parentheses

---

vnet_peering.yml

* ...
1. add resource group creation
2. add delete action
```bash
```
```bash
```
```
```
```bash
```

fix vnet peering sample

---

.github/PULL_REQUEST_TEMPLATE.md
.travis.yml
README.md
aci_create_with_acr.yml
appgateway_create.yml
appserviceplan_scale.yml
azure_rm_subnet/sub_with_nsg_in_other_rg1.yml
azure_rm_subnet/sub_with_nsg_in_other_rg2.yml
create_virtualmachine_with_subnet_in_different_resource_group.yml
keyvault_create.yml
mysql_create.yml
networkinterface_with_virtualnetwork_in_another_resource_group.yml
postgresql_create.yml
vm_create_existingvnet_deployjavaapp.yml
vm_create_with_nic_in_other_rg.yml
vmss/vmss-autoscale.yml
vmss/vmss-create.yml
vmss/vmss-scale-out.yml
vmss_extension/01-create-vmss.yml
vmss_extension/02-setup-httpd.yml
vmss_extension/03-update-instances.yml
vmss_images/01-create-vms.yml
vmss_images/02-capture-images.yml
vmss_images/03-create-vmss.yml
vmss_images/04-update-vmss-image.yml
webapp.yml

removed underscore
+ lowercase azure.azure_preview_modules, as included in the same pr by mistake

updated vmss samples

---

vmss_images/01-create-vms.yml
vmss_images/02-capture-images.yml
vmss_images/03-create-vmss.yml
vmss_images/04-update-vmss-image.yml

just removed references to preview modules

updating sample for ansible 2.8

---

vm_create_image.yml

* Generalizes VM from azure_rm_virtualmachine instead from the API.
* Uses new azure_rm_virtualmachineextension module.
* ...
```bash
```
```bash
$ ansible-galaxy install azure.azure_preview_modules
$ pip install -r ~/.ansible/roles/azure.azure_preview_modules/files/requirements-azure.txt
```
```
```
```bash
ansible-playbook vm_create_image.yml
```
```
TASK [Create VM Extension] ******************************************************************************* …
```

Adding support for 2.8

---

SIG_generalized_image/00-prerequisites.yml
SIG_generalized_image/01a-create-generalized-image.yml
SIG_generalized_image/02-create-shared-image-gallery.yml
SIG_generalized_image/03a-create-shared-image-generalized.yml
SIG_generalized_image/04a-create-vm-using-generalized-image.yml
SIG_generalized_image/05a-create-vmss-using-generalized-image.yml
SIG_generalized_image/06-get-info.yml
SIG_generalized_image/07-delete-gallery.yml
SIG_generalized_image/vars.yml

* ...
```bash
```
```bash
$ ansible-galaxy install azure.azure_preview_modules
$ pip install -r ~/.ansible/roles/azure.azure_preview_modules/files/requirements-azure.txt
```
```
```
```bash
```

For 2.9 release

---

rest/sql-managed-instance.yml

Fix playbook error on creating subnet part
ansible-playbook sql-managed-instance.yml

fix sql-managed-instance.yml
